// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOGMQYamcs6gHoN2vP52YnMVIYXF20VME',
    appId: '1:594022855564:web:f151fdbdf17db84ae6dca9',
    messagingSenderId: '594022855564',
    projectId: 'bima-gyaan-2025',
    authDomain: 'bima-gyaan-2025.firebaseapp.com',
    storageBucket: 'bima-gyaan-2025.firebasestorage.app',
    measurementId: 'G-KZW8MBZJXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARx0EbslTfhVhkW4Am-_DzUvJNGYaxStg',
    appId: '1:594022855564:android:87d0759be3f3af47e6dca9',
    messagingSenderId: '594022855564',
    projectId: 'bima-gyaan-2025',
    storageBucket: 'bima-gyaan-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5BV7TcwsinbPw-6ovt7T3Ftb4O-pBwQI',
    appId: '1:594022855564:ios:59827dbf8deb322be6dca9',
    messagingSenderId: '594022855564',
    projectId: 'bima-gyaan-2025',
    storageBucket: 'bima-gyaan-2025.firebasestorage.app',
    iosBundleId: 'com.example.bimaGyaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5BV7TcwsinbPw-6ovt7T3Ftb4O-pBwQI',
    appId: '1:594022855564:ios:59827dbf8deb322be6dca9',
    messagingSenderId: '594022855564',
    projectId: 'bima-gyaan-2025',
    storageBucket: 'bima-gyaan-2025.firebasestorage.app',
    iosBundleId: 'com.example.bimaGyaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOGMQYamcs6gHoN2vP52YnMVIYXF20VME',
    appId: '1:594022855564:web:8e8b30d70bf9c250e6dca9',
    messagingSenderId: '594022855564',
    projectId: 'bima-gyaan-2025',
    authDomain: 'bima-gyaan-2025.firebaseapp.com',
    storageBucket: 'bima-gyaan-2025.firebasestorage.app',
    measurementId: 'G-0B1WM37JQ3',
  );
}
